"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-27 06:34:04.874250
"""

from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("summary_source", sa.String(length=16), nullable=False),
        sa.Column("labels", sa.String(length=200), nullable=False),
        sa.Column("src_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("flow_count", sa.Integer(), nullable=False),
        sa.Column("blocked_count", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("first_seen", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.Column("assignee", sa.String(length=254), nullable=True),
        sa.Column("recommended_actions", sa.JSON(), nullable=False),
        sa.Column("narrative", sa.JSON(), nullable=True),
        sa.Column("draft_id", sa.String(length=64), nullable=True),
        sa.Column("tier3_pending", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_group_key"), ["group_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_last_seen"), ["last_seen"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_status"), ["status"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("seq", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=200), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)

    op.create_table(
        "bundles",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("created_by", sa.String(length=254), nullable=False),
        sa.Column("envelope", sa.JSON(), nullable=False),
        sa.Column("rule_count", sa.Integer(), nullable=False),
        sa.Column("stage_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.String(length=254), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("decided_by", sa.String(length=254), nullable=True),
        sa.Column("decided_at", sa.Float(), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("rule_id", sa.String(length=8), nullable=True),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_drafts_status"), ["status"], unique=False)

    op.create_table(
        "enrollment_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=254), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("uses_remaining", sa.Integer(), nullable=False),
        sa.Column("used_by_node", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "flows",
        sa.Column("flow_id", sa.String(length=64), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("src_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=8), nullable=False),
        sa.Column("bytes_total", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("enforced", sa.Boolean(), nullable=False),
        sa.Column("rule_id", sa.String(length=8), nullable=True),
        sa.Column("anomaly_score", sa.Float(), nullable=True),
        sa.Column("labels", sa.String(length=200), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=True),
        sa.Column("flow", sa.JSON(), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("verdict", sa.JSON(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("flow_id"),
    )
    with op.batch_alter_table("flows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_flows_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_alert_id"), ["alert_id"], unique=False)
        batch_op.create_index("ix_flows_alert_ts", ["alert_id", "ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_dst_ip"), ["dst_ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_node_id"), ["node_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_src_ip"), ["src_ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_flows_ts"), ["ts"], unique=False)

    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("agent_version", sa.String(length=40), nullable=False),
        sa.Column("backend", sa.String(length=40), nullable=False),
        sa.Column("applied_version", sa.Integer(), nullable=False),
        sa.Column("enrolled_at", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key_hash"),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("last_login", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "node_heartbeats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("applied_version", sa.Integer(), nullable=False),
        sa.Column("blocked", sa.Integer(), nullable=False),
        sa.Column("flows", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("node_heartbeats", schema=None) as batch_op:
        batch_op.create_index("ix_heartbeats_node_ts", ["node_id", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("node_heartbeats", schema=None) as batch_op:
        batch_op.drop_index("ix_heartbeats_node_ts")

    op.drop_table("node_heartbeats")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("settings")
    op.drop_table("rules")
    op.drop_table("nodes")
    with op.batch_alter_table("flows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_flows_ts"))
        batch_op.drop_index(batch_op.f("ix_flows_src_ip"))
        batch_op.drop_index(batch_op.f("ix_flows_rule_id"))
        batch_op.drop_index(batch_op.f("ix_flows_node_id"))
        batch_op.drop_index(batch_op.f("ix_flows_dst_ip"))
        batch_op.drop_index("ix_flows_alert_ts")
        batch_op.drop_index(batch_op.f("ix_flows_alert_id"))
        batch_op.drop_index(batch_op.f("ix_flows_action"))

    op.drop_table("flows")
    op.drop_table("enrollment_tokens")
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_drafts_status"))

    op.drop_table("drafts")
    op.drop_table("bundles")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_status"))
        batch_op.drop_index(batch_op.f("ix_alerts_severity"))
        batch_op.drop_index(batch_op.f("ix_alerts_last_seen"))
        batch_op.drop_index(batch_op.f("ix_alerts_group_key"))

    op.drop_table("alerts")
    # ### end Alembic commands ###
