"""Generate docs/configuration.md from the Settings model (run: uv run python scripts/gen_config_docs.py)."""

from __future__ import annotations

import inspect
from pathlib import Path
from typing import Any, Literal, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from neurawall.core import config
from neurawall.core.config import Settings

OUT = Path(__file__).resolve().parents[1] / "docs" / "configuration.md"


def _comments(cls: type) -> dict[str, str]:
    """Pull `#:` doc comments that precede each field in the class source."""
    out: dict[str, str] = {}
    pending: list[str] = []
    for line in inspect.getsource(cls).splitlines():
        s = line.strip()
        if s.startswith("#:"):
            pending.append(s[2:].strip())
        elif ":" in s and not s.startswith(("#", "def", "@", "class", "model_config", "return")):
            name = s.split(":", 1)[0].strip()
            if name.isidentifier() and pending:
                out[name] = " ".join(pending)
            pending = []
        elif s:
            pending = []
    return out


def _type(f: FieldInfo) -> str:
    t = f.annotation
    args = get_args(t)
    if get_origin(t) is Literal:
        return " / ".join(f"`{a}`" for a in args)
    text = str(t) if args else getattr(t, "__name__", str(t))
    for junk in ("typing.", "pydantic.types.", "pathlib.", "<class '", "'>"):
        text = text.replace(junk, "")
    return text.replace("|", "\\|")


def _default(f: FieldInfo) -> str:
    d: Any = f.default
    if d is None:
        return "—"
    if isinstance(d, BaseModel):
        return ""
    if hasattr(d, "value"):
        d = d.value
    return f"`{d}`"


def rows(model: type[BaseModel], prefix: str, env_prefix: str) -> list[str]:
    docs = _comments(model)
    lines: list[str] = []
    for name, f in model.model_fields.items():
        ann = f.annotation
        if isinstance(ann, type) and issubclass(ann, BaseModel):
            continue
        env = f"{env_prefix}{name.upper()}"
        lines.append(f"| `{prefix}{name}` | `{env}` | {_type(f)} | {_default(f)} | {docs.get(name, '')} |")
    return lines


def main() -> None:
    parts = [
        "# Configuration reference",
        "",
        "<!-- Generated by scripts/gen_config_docs.py from neurawall/core/config.py. Do not edit. -->",
        "",
        "Configuration is layered: **defaults → YAML file → environment → runtime overrides**. "
        "Every value is validated at startup and unknown keys are rejected.",
        "",
        "- **YAML file:** set `NEURAWALL_CONFIG=/etc/neurawall/server.yaml`; keys mirror the names below "
        "(nested sections as mappings).",
        "- **Environment:** `NEURAWALL_` prefix, `__` between section and key "
        "(e.g. `NEURAWALL_LLM__MODEL`).",
        "- `ANTHROPIC_API_KEY` is also honoured when `llm.api_key` is unset.",
        "",
        "## Server",
        "",
        "| Key | Environment | Type | Default | Description |",
        "|---|---|---|---|---|",
        *rows(Settings, "", "NEURAWALL_"),
    ]
    for section, cls in [("inference", config.InferenceSettings), ("llm", config.LlmSettings),
                         ("policy", config.PolicySettings), ("auth", config.AuthSettings)]:
        parts += ["", f"## `{section}`", "", "| Key | Environment | Type | Default | Description |",
                  "|---|---|---|---|---|", *rows(cls, f"{section}.", f"NEURAWALL_{section.upper()}__")]
    parts += ["", "## Production requirements", "",
              "- `environment: production` refuses to start without `auth.secret_key`.",
              "- Use PostgreSQL (`database_url: postgresql+psycopg://…`) for production; "
              "SQLite is for single-host trials.",
              "- The data directory holds the bundle-signing key: back it up and restrict access.", ""]
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
